language: node_js
node_js:
- "6.9"
cache:
  directories:
  - node_modules
after_success:
- npm run deploy
env:
  global:
  - NODE_ENV: "production"
  - secure: "n1idzmq13J+5bF6EtYO3yN8F4idjUxmz83Cbp0c27VYVvNPvt0bA0DvrLKF37q2UbAzMygFLajH5xQB79vFx+yO7+ZPWvtT/v+a90vRyR1RGeg+cg8MqLZxW1lOSA9CDXio+2L8uuIxqeJ0I7rG1gRKzFFBM+o0TBdxJ0lJzHQOEa9bm6wfzkgyRSH46Ow0f+gdYnTKuGzFft3d2fLssXK9SrT5ft2BGjUe3raN0Uu5EQ5Q7zg4GSIrC2ucTQZi3FjiWlKuEwhQx3CCQgP7FrJc4vkm+uGg/Fgxd/7Eh73BjYjMm9m7ui57T/iRRTvWmr0xbLc7Ulj2fgGhng5fe7MG9hXfXIU1d6nOiAu13Wy6I6gkjMtHGbNhAZ9xnauynTtvxxEY3sKI1LIsZzOmdFK1zGiuNHX+UZjLyCZLovvo62RGCiZb3CsQg7KIw8Isvj5fHrbmMetXCnVm2jnsL671digxg9Q8600l5HO6fvn9I5w/851qSqcRjAWuID7JlMu18X87uhfLxBWuYmIWZnFw33r6S/WKFbUsiKtGRdbRxK1sETYi3bCz0wHrT8N0F6sy07S7UnybgLXxjvZfQkyqgNjMEoNHxjnA+jspVL3ZsAjsiU7yWUtaDBsT9qLYnErdCYsl1qDXuQWdJ2+i+1I3EQnWe69GUxYR21Kru8qI="
